#                                  .:.-`
#     `......`.....`.....``..........-::.
#    .:-.--.-:-.--.//...-.:+../:...-`  `-.``
#    .+-:::--/--::-:+-----:+--//--:-` `-:..-`
#    .+/++//:/+////-+/////:o://+///:``-//-::-
#    .:/+ooo/`.///--+/+///.//-.+//+-..`./-```
#   ``.:/:-:::-../..... .-..-`::----...           ./-/+ssso/..://+++++/:.`
#  .`-o/++````.-`o-::::./::::::/-::::-`      `.-/odddddddddddhdddmmmho/::/:.
#  ../o/+:` ``.-.ooo++/+ooooo+.o+++o+/`   .+yhhhdmmddddddddmmmddddddddhs-  `
#  `.-//-``...-:.-+::-::-:-/--./--.--.`  .hddddddmmddmmdmmmddddddddddddddo`                                                                                                                                                                                                                                                                                                                                                                                ``...```
#   `.-..-----+//:/+//++///+///s/++//:`.ydmddddddmmmmmmmmddddddddddddddddm+                                                                 `.--://+++oo++++//:-.``````                                                                       `.-/+osyyyyyhhyyyyso++++++o/                                                                          .-:+osyhhhhyso/---.`                                                                           `.:/osyhhhhhhhhhhyys+/:.`
#     `.......+oo-.//.-+o+-ooo-/+-+o/. /ddmmmmmmmmmmmmmmdddddddddddddddddmh.                                                          `.:+oyhhhdddddddddddddddddddddddhhys+:.`                                                      `/:.``.:+shhddddddddddddddddddddddddddo-`                                                                  `.:oyhdddddmmmmmmmmmdddhhys+:-`                                                                 `-/shhddddddddddddhhhhhdddddhs/-`
#                           `      `.-/ommmmmmmmmmmmmmmmmmmmddddddddddddmmmdo                                                      `:oyhdddddddddddddddddddddddddmmmdddddddddho:.                                                  -yddhyyhhhhhdddddddddddddddmddddddddddddmho-                                                             `-oyhddddddddddmmmmmmmmddddddddddhs/-`                                                         `.:ohdddddddddddddddddddddddddddddddho-`
#                               .:+yhdddddddddddmmddddddddmmmmmmmmmmmmmmmmddm:                                                  `-oyhhhhhdddddddddddddddddddddddddddddddddddddddhs-`                                              /dddhhhhhhhhhhhhhhhhddddmmmmmmddddddddddddmdds-                                                         .+hddddddddddddddddddmmmdddddddddddddddy+-                                                    .:shddmdddddddddddddddddddddddddddddddddddh+.
#                            ./shdddddddddddddddmddddddddddddddmmmmmmmmmddddm:                                                `/yhhhhhhhhhhhhhhhhhhddddddddddddddddddddddddddddddddy-                                           .smddhhhhhhhhhhhhdddddddddddddddmddddddddddddmdddo.                                                     -shddddddddddddddddddddmmmddddddddddddddddddy/`                                              `/ydmmmmmddddddddddddddddddddddddddddddddddddddho.
#                         `:shddddddddddddddddddmddddddddddddddddmmddmmmmddds`                                               :yhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddds.                                        /hddddddddddddddddddddddddddddddddmdddddddddddmmdddh-                                                  .oddddddddddddddddddddddmddmddddddddddddddddddddh+.                                          .ohmmmmmmmmddddddddddddddddddddddddddddddhhhhhhhhhhh/`
#                       `/yhhhhhhhhhhdddddddddddmmdddddddddddddddddmmdddmmh:                                               `ohhhhhhhhhhdhdddddddddddddddddddddddddddddddddddddddddddddh/                                     .sdddddddddddddddddddddddddddddddddddmdddddddddddmmmddd:                                                :hdhhdddddddddddddddddddmh::ohdmdddddddddddddddddddh+.                                      `+ddddddmmdddmdddddddddddddddddddddddhhhhhhhhhhhhhhhhhds.
#                      -ydhhhhhhhhhhhhhhhhddddddmmdddddddddddddddddddmmdddds-                                             .yddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddo`                                  :hdddddddddddddddddddddddddddddddddddddmdddddddddddmdmmmm:                                              +dhhhhhhhhhdddddddddddddmy-....:shmdddddmdddddddddddddh/`                                   .hdddddddmmdddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhh:
#                     /ddddddddddddddddddddddddmmmmdddddddddddddddddddmmddddd+`                                          -hdddddddddddmddddddddddddddddddddddddddddddddddddddddddddddddddy`                                +dddddddddmddddddddddddddddddddddddddddddmddddddddddmdddmmdo`                                           odhhhhhhhhhhhhhhhhdddddmdo-.......-+hddddmddddddddddddddds`                                 :dhhhdddddmmmdddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdo`
#                    /mddddddddddddddddddddddddhhmmdddddddddddddddddddddmdddddy`                                        -dddddddddddmmmdddddddddddddddddddddddddddddddddddddddddddddddddddy`                              /dddmddddddhddddddddddddddddddddddddddddddmdddddddddddmdddddd`                                          +dhhhhhhhhhhhhhhhdddddddy/...........-odddmddddddddddddddddy.                               :dhhhhhddddmmhddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhdddddds`
#                   -mdddddddddddddddddddmddddd+:sdmmddddddddddddddddddddmdddddy`                                      `hdddddddddmmhoydddddddddddddmmddddddddddddhysohdddddddddddddddddddms                             -ddddmdddddm+yddddmdddddddddddddddddddddddddmddddddddddmmmmddds                                         -mdddddddddddddddddddddy+-..............-sddmddddddddddddddddh`                             -ddddddddddmds:/hddddddddddddddddddddddddddddddddddddddddddddddds
#                  `hmdddddddddddddddddmmdddddy-../ydmdddddddddddddddddddmmdddddo                                      +dddddddddmds::ydddddddddddddmm+yddddddhy+:.` .yddddddddddddddddddddm:                            yddddmdddddm:/dddddmdddddddmddddddddddddddddmmddddddddddmmddddh`                                       `hddddddddddddddddddddy+-..........-----...+dmddddddddddddddddds                            `ddddddddddmh/-..:sddddmdddddddddddddddddddddddddddddddddddddddddm/
#                  +mmddddddddddddddmdddddhhdh-....:sddmddddddddddddddddddmdddddm-                                    `hddddddddmd+--:odddddddddddddmm:/hddhy+.`  `./ydmddddddddddddddddddddd`                          .mddddmmddddd::/hddddmdddddddmmdddddddddddddddmddddddddddmdddddd+                                       /mdddddddddddddddddds/--......-/oo+/::::://:/dddddddddddddddmddd:                           smddddddddmy:-....-+hdddmmddddddddddddddddddddddddddddddddddddddddd.
#                 `dmmddddddddddddmmhshddhydh-...+yho::ohdmddddddddddddddddmhyyhdy                                    .mdddddddmd+:-::/mdddddddddddmmmhho/o-`  ``./yddddmdddddddddhhddddddddm:                          :mdddmm+ddddm////yddddmmddddddmmmdddddddddddddmmdddddddddmhyyhdds                                       yddddddddddddddddho:--....../yhs:...........-yddddddddddddddmdddh`                         -mddddddddds::-------:sdddmdhddddddddddddddddddddddddddddddddddddddms
#                 :NNddddddddddmmdddshddyhdy-..+dmo.``..-ohdmddddddddddddddd--:/sd`                                   /mdmddddddo/:/+shmddmddddddddmmms:..-````.+hddddddmmdddddddd+/sdddddddmy                          :mdddmy:odddm++oyydmdddmmmdddddmmyddddddddddddmmdddddddddm/-::+hs                                      `mdddddddddddddmdo:--......+hms-....--:://:-.`+ddddddddddddddmdddm:                         smddddddddy++/:://osyo//yddmdsshddddddddddddddddddddddddddddddddddddm.
#                 smNdddddddmmmdy+/hmdmyddo..`/mh:```-:--.-:sdmdddddddddddddy+//+h/                                   /mdmddddm+......:+dddmmdddddddmm:-.-:...-odmmddddddmddddddddy/+hdddddddd                          .mdddmy/-:hdm+...:odmmddmmmdddddddoohddddddddddmdddddddddmy++/+od`                                     -mddddddddddyo/+ydh/....../mh/.`.-:--.---:/++-/ddddddddddddddmmdddy                         mddddddddh+:........:odds/sddmy+mdhdddddddddddddddddddddddddddddddddm+
#                 hymdddddmmmds+/+hddsddy:.```.-```.:-...----:sdmdddddddddddy::::/y                                   .mdmdddmh/:-----.-+dddmmddddddmm+:/-`..---:oydmmmmmmddddddddh::/mddddddm`                          omddmo.-:/ydh:-..../sshdmmdydddddmh:-/sdmmmmddmmdddddddddy:::::ys                                     -mddddddyo+::::-.-+o...```.:.``.:-...-----:/+y/mdddddddddddddhmdddm`                       -Ndddddddm/::/::--:-..../s-.-ohdmdo:/oyhddddddddddddddddddddddddddddddy
#                 ysmdddmmmds-`.oddysho:..````````-/:+osyhddddddNdddddddddddd::::/s                                    ydmmddm/--.``.-:::/dmmdhdddddmmy/:+oyhhddddddmNNmmmddddddddd::/mddddddm`                          `sddmy+/:-.:s:-:::....-/sdmmyoydddddsyhdmNNmmmmmdddddddddy:::::ym-                                    -mddds+:-.``.-::-.````````````-/:/osyhdddddhhmdmdddddddddddddhmdddm:                       +mdddddddmso/:-..`.-::-..````..:ohmhs+:/sdNNmmmdddddddddddddddddddddddd
#                 osmdmmmmy:--+dho:++/-.`````````:shNNNNNNNNNNNNNmddddddddddd::::o/                                    .dmmmmh:--...----///sdmdoydmmmmmhNNNNNNNNNNNNNNNNNNddddddddd::smddddddm                             +mdm/:---..----:/:.```.-/sddysdNNmmmNNNNNNNNNNdddddddddy:::::dmh`                                   .mmds::--...----:/-``````````:ohNNNNNNNNNNNNNNNmdddddddddddddmmdddm+                       omddddddmdy::---...---:/-.```````.-odmmNNNNNNNNNNNNmddddddddddddddddddm`
#                 `ommmmms+osdNNddhyo/+:````````/mNmdymNNNNNNNhyhmddddddddddd:::/y`                                     :mmmmy+oshhdddhyo/+::sdd+-+ymmmNdyNNNNNNNNyyhNNNsmddddddddh:/ddddddddh                             .yyms/+syhddddhs+//.``````.:dNNmhhNNNNNNNmyhdNdddddddddy::::smdmo                                   `moyo/+osyhddddyo/+:````````:mNNdymNNNNNNNhyhNNmdddddddddddddmmddddo                       smddddddhoy//+syhddddhs+//.```````.hNNdyhNNNNNNNmydmddddddddddddddddddm`
#                  +mmmmNNNNNNNNNNNNNNdy:``````:mh+..-ohyhyohho:/mddddddddddd::/s`                                     -oNNNNNNNNNNNNNNNNNhs-`./o/`/myos/-ohyhsohh+:+NNoyddddddddmo/ddddddddm+                           `/yhhNNNNNNNNNNNNNNmyo```````sms:.-:yyyhoshh::sNmdddddddmy:::omdddm-                                 -+mymNNNNNNNNNNNNNNdy:``````-mh+-.-+hyhyoyhs:/mNmdddddddddddddmmmddds                       omddddmNydNNNNNNNNNNNNNNmyo``````.hms:.-:hyyhoshh:smddddddddddddddddddm`
#                  `mmmNNNNNdyo:-sNNNNNNd.`````y+::..::. `  +o:`+mddddddddddy:+h.                                      `dhNNNNNNdy+:-sNNNNNNh.````.y+:-..::` .  +o-`ohy/mdddddddddodddddddddm.                            /hdNNNNNmhs/-:dNNNNNN+`````:y/:-.-:: `` .oo`.ydmdddddddms::ymdddddd`                                `hhNNNNNNdyo:-oNNNNNNm.`````s+::-.::. `` /o/`/hhmdddddddddddddmmmddds                       :NddddmhmNNNNNmhs/-:mNNNNNN/`````/s/:-.-:- `` -oo`/mddddddddddddddddddd`
#                  /dmmNNNo/:::-+syosh:yNo````./.`   .--`  .:/.-ymddddddddddsym:                                       ++`-mNN+/:::-+syoyh:hN+````./.`   ---`  .:+`-s:/dddddddddmmmddddddddmo                            `y.`+NNh//::-:ssyohs/mm-````::``  `--.` `-:/ +oomdddddddm++dmddddddmy`                               :s`.hNNo/:::-/syosh/sNs`````/.`   .--`  .:/-.s//ddddddddddddddmmmdddo                       `mddddd.`oNNh/:::-:sssoho/Nd.````:-`   `--.` `-:/`smdddddddddddddddddmh
#                 `y.ymmmds.````.oo-  .sho/+/::`      .....--/:oomdddddddddmmm:                                       `y.`:sodo`````-oo.  -sho/+/::`      .....--/:o-:ydddddddddmmmddddddddd`                            /o``s/hh/`````/o+` `/yh+++/::      `-..`--:/++-sddddddddmdmdddddddddmo                               y-`-mmds.````.oo-  .ohs/+/:/`      .....--/:o::-hdddddddddddddmmmddm+                        omddm/``ymmh:`````+o/` `/hy/++/:-      `....--::+ymdddddddddddddddddm/
#                 o/.-mmhys/     .::.`./s:-.-:/.`   ```.......--sddddddddddNd-                                        s/.-y:oss/     .::.`-+s:..-:/.`   ```.......---:mddddddddmmmddddddddm-                            .y../s:sss-     ::-.`-oo-..-//.   ````.......--.oddddddddmmmddddddddddm/                             ++.-ymhys+`    .::-`./s:-.-:+-`   ```.......---..hdddddddddddddmmmddm/                        `dmmh..+mdhso.    `::-``:s+-..-/:`   ```........-ydddddddddddddddddmd`
#              :ooh/-+oddy+/+.````-:--://``````---.......-----..hdddddddddmo`                                      :ooy:-o/ `/+/+.````-:--:+/``````--........-----...yddddddddmmmddddddddm+                          `+oyo::y. -+:+:.```.::--:+-`````.--........-----...ydddddddmmmmmddddddddddm-                         -ooh/-/mmmyo:+-````-:---/+``````--........-----..``.hdddddddddddddmmmddm:                        .syd+::dmmhs:+:.```.::--/+-`````.--........----.-ddddddddddddddddmdm:
#           ./y/``./oy.+mdh:::.`````.--.````.``````............:mddddddddds                                     -/y/``.+oy`  `s:::.`````.--.````.``````.............:mdddddddmmmmdddddddmh                         :os-``:oos   :s-:-.````..--````````````..............hdddddddmmmmmdddddddddddh`                     ./s+.`./oymmmdd/-:.`````.--.````.``````................hdddddddddddddmmdddm:                     `:os-``:oommmmdo-:-`````..-.````.```````...........omdddddddddddddmmmm+
#          :o--:+/-.od `ddmy:++/----.`````-...`````````........sdddddddddh`                                    /o.-/+/-.sh    /s:++/---..`````-...`````````.........yddddddddmmmmdddddddN:                       `s/.-/+/.-d+    y//++:---.``````-...`````````..........dddddddmmmmmmmddddddddddms                    :s--:+/:.+mmmmmmh:++/:---.`````.....`````````...........ddddddddddddddmmdddm-                    `s:.:/+/.:mmmmmmm:/++:---.`````.-...`````````....../ddddddddmdddddmmmmo
#         /y//:.-ys::d- /mmy/-sy-`````````-/::.````````.......-dddddddddm-                                   `+y//:.-ys::d.  .+s/-sy.`````````:/::.````````........-mdddddddmmmdddddddddd`                      .so//-`oy+-oy   -so::h+.`````````//:-````````..........:mdddddmmmdmmmmdddddddddddm/                  /y+//..ys::hmmmmmy/-oh-`````````-/::.````````...........:mdddddddddddddmmdddm-                   -so//-`oy/-smmmmmdo::h/`````````.//:.````````....../ddddddmmmddddmmNmd/
#        o+``.-o-y+o:+h:+s-`-so-```..``````.-.````````........sdddddmddm/                                    s/``.:o:soo:+y-+o-`-so.```..``````.-.````````.........omddddddmmmmddddddddms                      .y-``.+//ss/:yo:o+.`/y/.``..``````...````````...........oddddddmmmdmmmmddddddddddddd.                ++.`.-s:soo//dmmy:`.ss-```..``````.-.````````...........+dmdddddddddddddmmdddm-                  -s.``.o/+os/:hmmh+.`+y:.``..``````.-.````````.....-sdddddmmmmmmmmyhmmy.
#       .y`:+:.o/o+/soy/-``/ds.``.....`````````````........../mddddmddm+                                    .y`/+:.s/s/+soy:-``+hs.``.....`````````````-..........-dddddddmmmmmdddddmddmo                      o/`+/-:s:s:ooos-.`.sh:```.....````````````.-`.........-smdddddmmmmmmmmmdddddddddddddy`              `h.:+:.o+++/soy/-``/dy.``.....`````````````.-`........./hmmmdddddddddddddmmdddm-                  s:.+/./s/s:ooso:.`-yd:```.....````````````.-`...-+dmddmmmmmmmmho/yds-`
#        y-`-o//s+o:...```ommm+........``-.......-/+-........hddddmmdmo                                     `y-`-s/+s++:...``.o+.h+........``-.......-/+........./ymddddddmmmmmddddddmdmh`                     -s`./o:s+s:-...``-y:-y:........`.-......-:+/........-+hmmdddddmmmmmmmdmmddddddddddddm+               s:`-o//y/o:...```+mmmo........``........-/+-........:sdmmmddddddddddddddmmdddm-                  :s`./o:s/s:-..```:dmmh-`.......`.-......-:+:.-/sdmmmmmmmmdhs+--+s+.
#        -y``.osys+``````s+smmmy:.......`-/+//////-.......-/ymdddmmmms`                                      :s``-osys/`````.s/ .ddo:........-/+/////:-.......-/yhdmdddddmmmmmdddddmdmNmm+                      s:``/ssys-`````-y.  ydo-........:+//////:-.......:oyhdNmddddmmmmmmdmdmmdddddddddddddd.              .y``.osys+``````ommmmmh/.......`-/+//////-.......-/shhmmmmddddddddddddddmmdddm-                   y-``/syss.`````:y-+hmd+........./+//////:/oyhddmmmmmmmh:.`   ..`
#         y-``.//-``````oo `hmmNdy/-.........--........-:oyhmmddmNmms`                                        y.``./:.``````o+  yd--dy/-.........--........-:oyhhhdmddddmmmmmmdddmdohdmydmo`                    -s```:/:.`````.y-   sddho:.........---........-/shhhhymdddddmmmmmmdmdmmdddddddddddddmo               s-``.//-``````+mmmmmmmmy+-.........--.........:+yhhhydmmmddddddddddddddmmdddm:                   :o```:/-.`````-y.  `./sy+:.........---....----:ohdhhyyo
#         +/```-.``````+s`  .dmmNmmdyo/-............-:oyhhhdmddmmmmo`                                         o:```-.`````.oo  +y. .mmmhy+/-............-:oyhhhhyodmddddmmmmmdddhdm-.odh:+hh/`                   y````-.`````-y:    sdddmmhs+:-............-/syhhhhs/+mddddmmmmmmmdddmmdddddddmddddddm`              :+```.-``````/mmddmmmmmmmdyo/-............-:+yhhhhyo:hmmmddddddddddddddmmdddm:                   `y```.-``````-y-       `./++/:.............:/syhhhys/oy
# `````  `o+:.```````-s+` `  :mmmmddmmd/++//::--:/+syhhhhhymmmmdmmy`  `````````````````````````````````````  -hs:.```````:s+` .:`  :mmddddddhso//:--:/osyhhhhhhyyydmddmmmmmmmddm/dy`  -oy-`-//.  ``````````````  y`````````.+y-  `  +dddmmmmmdhyo+/::-::/oyhhhhhys+::+mddddmmmmmmmdddmmdddddddmmdddddm/  ``````````  :+`````````-smmddddddmmmmmmmddhso//:--:/+syhhhhhyo/::smmmddddddddddddddmddddm: ````````````````` `y`````````.+s-  ``````    `-:++///::-::+oyhhhhhyo/::/d`   `````````````````````````````````````
# ````` .yy-.:/:-...ss-  ```  /mmsmmmmh  `..:+sydhhhhyyso+smmmyhd/::`   ```````````````````````````````````  syossso++//sd-        odh-hddddmmmmdddddddddddhhhysoodmddmmmmmmddmo-d. ``  ``      ``````````````  :o````````:y+` ```  +mddmmmmmdmmmmmddhdhhhhhyyso/::/++mdddmmmmmmmmmddmmdddddddhmddddddy  ``````````  s-```````.oymdmddddddddmmmmmmmmmmmddddmhhhhhyys+/:::::dmmdddddddddddddmmddddm: ````````````````  /+````````/y+` `````````````   ``.--::hhhhhhyyso/:::::sho.   ```````````````````````````````````
# ````  /hyyo:.`.-:/o+  `````  /mssmmms  `://::hhooooo+/::ymmhos.  .s/-.`     ```````````````````````````  -/hyooooooosssd` ````` .dh. /ddddmmosddmdsssysssoooossohmddmmmmmmdmo`/-  `````````````````````````` `y-```````.+o  ````  ymddmmmmmdmmmmdyo+dooooo++/::++-`:mmdmmmddddddmdmmddddddddsdddddddd  `````````  :s````````.h.hdddddddddddmmmmmmmmmmmmmmdooooo+/:::::/oyhyddddddddddddddmmddddm: ```````````````` `y.```````.o+  `````````````````      .dooooo+//::::--.-dNmo:.``     ````````````````````````````
# ````  yyyyyyyo/-.`-y. ``````  /d:hmmh./o:.:ydy/:::::::::dmd-.`   /hyyyyso+:-.`  `````````````````````  -sysssyyysssssshs  ````  sy.   ydddmmy:ymdyooosooooooossshmddmmyyhddh+::-.   ```````````````````````  /o`````````/o ````` .mmddmmmmdddddh/./yo:::::::/++.   +mmdmmso++sooyyhddddddddd+dddddddm` `````````  y-`````````y.ydddddddddddmmmmmmmmmmmddy/:::::::::/oyys/-.hdddddddddddddmmddddm: ```````````````  ++`````````++ ```````````     ``.-:yhhy+:::::::::---.``.yNms/+oo++/:-.`  ````````````````````````
# ```` `dysssssyyyysyho  `````  -syyddhs/.-/oNN/---------/dmo-`   .yyyyyyyydhyys/.  ``````````````````` -hsooooooooosssssh` ```` -/``.:/yddhhyhhhsssysssoossssyyssodmdmmooooossssyss/` `````````````````````` `h-`````````/s ````  odddyysso+syos: -/o-------/s:     smmdmmo/:o/  ``.:/shddddd-dddddddm` ````````  /s``````````h.sdddddddddddmmdhhyso+/yh:.-------:+yhs/-````ddddddddddddddmmddddm: ``````````````` `h.`````````++ ````````  `-/++oooymNNd+-----------..`````sNNy```..-::/+oo-  ``````````````````````
# ```` /hssssssssyyyyh/ ````  .+dhhhhyo/://./NN/`......-smmd/-/.  /hyyyyyyhyyssyhh+` `````````````````  syooo++++++oooosoyo  ``` `./syssssoosssooooooosssssssooooooymmmmooooooooooooyy/` ```````````````````  /o``````````/s ```  `dy+-.`   -o++/.//:s......:s//.   -hdmmmmo:+/         -sdddy.mddddddd  ```````` `h-``````````h.odddddddddhs/:-..`````sh-``....-+yy+-``````.dddddddddddddddhddddm: ``````````````  o+``````````+o `````  `:oo+:-../ymmdo-```.......`````````/Nmd.``````````-oo. `````````````````````
# ```  sysssssssssyyyd. ``  -ohmhhhhyo/o+-``+mN/`````-odmmm+o--:-`oyyyyyyhyssssssyhy-  ```````````````  hsoo++++++++ooooood. `  -oysoooooosssooooooooooooooooooooooodmmmsoooooooooooooys. `````````````````` `h-``````````/s `` `-+/.      :o+/o//yo/y.````:s//:+` -/yymmmm:/s`          `sdd::mdddddmh  ```````` :y```````````h.+dddddddh/-```````````oh-````.+yy/.````````-ddddddddddddddy:+dddm/ `````````````` `h.``````````+o ```  `/s+-.```:smNds-`````````````````````-mmm:````````````:y+` ```````````````````
# ``` .dssssssssssyyyh    -sddddhhhs://-````+mN:```.+dmmy+y`//..+oyyyyyyhhsssssssssyh+` ``````````````  ysoo+++++++++oooooh/ `-sysooooooossooooooooooooooooooooosoooodmmhooo+++++++oooosh/  ```````````````` :y```````````/s  `:+:`       :o+/:+::s:/y-```:s/::/+/-/-sydmmd:o/            .yy smdddddm+ ````````  y:```````````h./dddddy/.`````````````/d/-../yy/.``````````:ddddddddddddddy-`-ymm/ `````````````  /s```````````o+ `  `+s+-````:omNmy-```````````````````````.dmm+`````````````.os. ``````````````````
# ``` /dssssssssssyyys  -sddhhdhhy/:/:``````omN:`.+dmmy/.-:`.o..sdyyyyyydyssssssssssshs. `````````````  ysoo++++++++ooooooh--sysooooooossooooooooooooooooooooooosooooodmmsoo+++++++++ooooho` ``````````````  y/```````````+o`:+:`       `/o+/--+::s-.s:`.+o::+++///--+yymmd:s.             :s/dmdddddm. ```````` -h```````````.d.:dddy:.`````.-.``....:shs++sds.````````````/ddddddddddddddy-``.omo `````````````  h:```````````o+  `+s/.````-ommmh/.`````````````````````````ymNo```````````````:y: `````````````````
# ``  yhsssssssssyyyh+-sddhhhhdhs/::.`````:ohNN/+dmmh/.`````.o``yhyyyyydhssssssssssssshh- ````````````` ssoo++++++ooooooohsshysooooosyysoooooooooooooooooooooooosoooooohmhoo++++++++++ooooyy. ````````````` .h.```````````oy+:`      `.:+s+/---+//s..+/.+/-+o:://:---:yommm/y.              :ohdddddms ````````  o+```````````.d`/my:...``..:+++oossyyho.``.-yhso+:-..``````+dddddddddddddds-````/y: ```````````` -h````````````s/`+s+...``./hdyo/.```````````````````````````sNmy.```````````````-y+` ```````````````
# `` `myssssssyyyyyydhddhhhhhdy+:-.```````ddmmNmNNNo-```````-+`.hyyyyyhhhssssssssssssssyd: ```````````` ss+o++++ooooososddhhyyyyyyyhysooooooooooooooooooo+++++++ooooooooddhooo+++++++++oooosh: ```````````` +o````````````sy-``  `.-/oo+/:-----+:-s../+/-:+////:------y/dmm/s.`             `:/hdddmd. ```````` `h-```````````-dos/....-:+syyyyyyyyhhhd+....+dhyyyyyyso+:..`odddddddddddddds-`````-y/ ``````````  o+```````````.yss+.....-:/+:.```````````````````````````````+Nmd:````````````````.ss` ``````````````
# `` /dsyyyyyyyyyyyyddhhhhhho:..`````````-mdddmmmmd/````````/:`.dyyyyydhhyssssssssssssssyd/ ``````````` ss+oooooooooooodmhyyyyhhhsooooo+oooooooooooooo++++++++++ooooooooshhyooo+++++++++oooosh: ``````````  h:```````````.ys----:+o+/:---------/::s../:-+/::/:--------+/smmsy-.`             -.-sddm/ ````````` -h````````````-d/...-/syyyssyyyyyhdyo:/oo++o++hdhyyyysssyys+ydddddddddddddds-``````.y+ ````````` `d-```````````.h+--://++//-.`````````````````````````````````:mmmo``````````````````os` `````````````
# `` shyyyyyyyyyyyyydhhhyo:-..-----.`````+mmmmmmmd:```...---o.`-dyyyydhhhysssssssssssssssyd/ `````````` oyooooooooooooyhdyyhdhsooooo+++++oooooooooo++++++++++++++ooooooooshsoooo++++++++ooooooh/ ````````` .d.``````````..so--/so/-------------//:o:-.////::-----------::dmhy:..`             - `+ho  ````````  o+```````````.:s..-ohysssssyyyyyds:.``````````.odyyyssssssssddddddddddddddds-```````.y+ ```````` -h```````````..y-.sdhmhshhyyo..--.`````````````````-+//ooo+:+smNNh-``````````````````+y` ````````````
# ` `dyyyyyyyyyyyyyydhho-.`````..`..---.`oNmNmmmo:.----...`.o` +hyyyhhhhhhysssssssssssssssyd+  ```````` +yooooooooososshdhdhsoooo++++++++oooooooooo+o+++++++++++++ooooooooyhyoooo+++++oooooooooh/ ```````` /s``````````...y+/so:---------------:+-o/:++::----------------+mms+-..`            ``  .+:` ```````  h:``````````../o-ohysossssssyyyd+```````````````ohssssssssssddddddddddddddds-````````.yo ``````` +o``````````..-y-+ddsossssyhdhydyso-``````````:oyoshdmdhhhhhmdhdmmd/``````````````````+y. ```````````
# ` -myyyyyyyyyyyyydhy:`         ```...-+mmNmmmd/-.....``` -/  shyyydhhhdhhysssssssssssssssyd+ ```````` +yooooooooooooodddsoooo+++++++++oooooooooooooooo++++++++++ooooooosyddysoooo++oooooooooooh/ ``````` s+`````````...:hss:------------------+:+s+:--------------------smhs/-..`               ``-+-  ````` `d.````````....oohyosssssssssyyyh````````````````+hssssssssssddddddddddddmddo-`````````.so `````  y/`````````...:yymdhhhddyy+/+oshhhdd/.``.`-/+yhhhyys++osys++oyhhhdhho``````````````````+y. ``````````
# ` :dyyyyyyyyyyyyhds.                `.dmmNmmNo-.``       /- `dyyyyhdhhmdhyysssssssssssssssyd+ ``````` oyosoooooosooosmdooooo+++++++++ooooooooooooooooooooo++++oooooooosshdyhyyoooooooooooooooooh/ `````  h:````````....+ho--------------------/+/:----------------------:ymsyo:-..               ..`/+` ```` -h`````````...-hdsossssssssssssyh-````````.````./hsssssssssssddddddddddddmdm+-``````````.so ````  d-````````....ommhddyhhhyhhyhyy+/ohdhd:-./dhdhs+ohyhyyhyhhhohdyssdddy/``````````````````/y. `````````
# ` +dyyyyyyyyyyyhdh.                  +NmmmmmN+`          o` .dyyyyydhhd/dhhyysssssssssssssyyd+ `````` syosooooosooooymsoooooooooooooooosssssssssssooooooooooooooooossssshm-/dyysooooooooooooooooh/ ````  d-````````...-ys::-------------------//----------------------:///hmddh+--.`             `--./o ```` /y````````..../ms+oosssssssssysyyhs/-.````-.-/oyyssssssssssssmdddddddddddmdd:-````````````so ``` `d-````````...-dmdhhhyyyyhhhhhyyyoyyhNNyo-hNmyddhyyshhhhhyyyyddddydMh`y+``````````````````/h` ````````
# ` +dyyyyyyyyyyhhd/                  `dmmmmmmN:`         .+  /hyyyydhhhd -hdhyyyssssssssssyyyyd+ ````` oyosooooosooosdhssyysssssssssssssssssyyssssssssssssssssssssssssssydm` :hyyysoooooooooooooooh/ ``` `d-````.......+h/::::::::::::::::::::/+:::::::::::------::::://///+dmmdh/---..`          .-:-:y` ``` /y````.......-ydyysssssssyyyyhhhhdhhdhhyyyhhdhyyyyyssssssssssmdddddddddddNdh:.````````````.so `` `d.````.......oMmdyyhyyyyhhhhhyhhhdmmmNNmdNmmNhdhhhyhhhhhyhhhhhhmdNMs `so.`````````````````/y` ```````
# ` /dyyyyyyyyhhhdh.                ``+mddmmddN:.         -/  shyyydhhhhh  .ydhyyyyyyssyyyyyyyyyd/ ```` +hosooooosooshmyyyyyyyysssyyyyyyyyyyyyyyyyyyyysssssssssssssssysyyydh   .yhyyysooooooooooooood: ``  d:`.........:yy/////////////////////o////////////////////////////ohmmmmy:-----..`     `.--/::s- ``` :h.`........-+mhhhhhhhhhhhhhhhhhhdhhhhhhhhhhdhhhhhhhhhhhhhhhhmdddddddmddmNmy:.`````````````.y+ ` `d-`.........:hNdhhhhhyhdhdddddyhhhmNNNNNNNNNNdhdhydddddhdhyhhhhhdNM/   +y-`````````````````+y````````
# ` -mhhhhhhhhddddy:-.`````````...---:dmdmmdddN/---.......+-  hyyyhhhhhds `  +dhhyyyyyyyyyyyyyyyyd: ``` :dssoooosoosyhmyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssyyyyyhmo `` `odyyyssoooooooooooood- `` yo........-:+hy/////////////////////o///////////////////////////+shdmmh:s----------.--:::---.-o` `` .d:........-:+dhhhhhhhhhhhhhhhhhhddddddddddddddhhhhhhhhhhhhhhmdddddddmddmNms:.``````````````.h/   h+........-:/hNmmddhhyhdhhdhhhhhdmmNNNNhmNNNmmmdhhddhdhhdhyhddmmmMN. `` -y/`````````````````os```````
# ```hddddddddddddh+-----------------+NddmmdddNo----------o. `dyyhdhhhhd+ ``` -hdhyyyyyyyyyyyyyyyyd- `` `dhyssssssyyhymhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydm: ```` :hhyyyysooooooooooosh. ` :h:--.---::/s+h+++++////////////////o+/////////////////////////+sydmmh` so---:----://::.``````-o` `` yo:--.--:::::hhhhhhhhhhhhhhhhhhhddddddddddddddddddhhhhhhhhhdmddddddmmdmNmmmo````````````````.h:  /h:--.---::::sNmmdddmdmmmhymmmmmmmmNdddsydhNmmmmmmmmdshmmmdmdddmNNh ```` `so.````````````````ss `````
# `` -mdddddddddddhy/----------------ymddmddddms----------o. .dyhdhhhhhd: ```` `sdhhhyhyyyyyyyyyyyyd- `` :dyyyyyyyyyyyhdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdhd` ````` `shyyyyyyysooooooooyh.   ss:::::::/s::sy+++++++++++++++++++++o+++++++/////////////+++++syydmo` /mh/--::://:----````````/+ `` .d/::::::::::/dhhhhhhhhhhhhhhhhhhhhhhhhddhhhddddddddddddddddmmddddmmmdmmmNmmy.```````````````-h- `yo:::::::::::dmdmmmmmNmNddmNNNmmNmyo++++ooyNNmmmNmNmddNmNmmmNmNmd+ `````` :y:````````````````so ````
# ``` :ddddddddddddhho:-------------:mdddmddddmh----------o` -dydhhhyyyd. `````` :hdhhhyyyyyyyyyyyyhd` `` :dhyyyyyyyyyyhdhyyyyyyyyyyyyyyhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhyhs ```````` :hhyyhysosssssoooshh`  `oy/:::/o+:--:+ys+++++++++++++oosooooooooooo++++++++++++++++sysohy-  .s:`/++++/:-----::://////oy```` -ho::::::::::/hdhhhhhhhhhhhhhhhddddddddddmmmdhhhhhddddddhhdmmdddmmmmmNmmNdddd+..`````````````-h. `sy/::::::::::yNNmmNNmmmmmmmmNNds+///::://+ohNNNmmmmmmmmmNNNNNhym- ``````` `ss-.``````````````y/ ```
# ```` `+hddddddddddho+oo+//:------.+mdddddddddm:...------o. -dddhhyyyyh````````` `odhyyyyyyyyyyyyyhdy ``` `+yhhhhyhhhhhysoyhhhhhhhhhyyyssssssyssssssyyyyhhyyyyyyhhhhhyyyd/ ````````` `oddyyyyyssoooooyyhs `` -syoo+:::::/+ooosssssosoooo++//////o/////+oossooooooooossso+/+h` ` ````````/s:::/+o+/:.`````.h: ``` `/sso+//++osssmhddhhhhddddmmdddddddddddddddddmdddhhhhhhddmmmmmmmmmmmmmmmdddhmh/--::..````````/y   -sys++//+oossyshmmmmNNNNNmdyo///oshdddhys+/+sdNNNNmNNNNNmdysoyd `````````` :yo:--:-.````````.h. ``
# `````````-:///:-.```` -dho+...````smdddddddddm/.````..--o- -ddhhyyyyhs ````````` .dhhhhyyyyyyyyyyhhd. ```````-:///:-.``````.-sdyysssssssssssyssssssssssssyyyyyyyysssssym` `````````` `dhyhyoooooooooyyyd````` .:////:::-.````..-yo/////////////o///////////++++++++//////oo ``````````` .ooyo-```````````+s ````````-:///:-.` y+mdddmmmdddddddddddddo/hdddddddddddddmmmmdmmmmmmmmmmmmdmdddmymmmys/````````````d. ````.:////:.``````.-:mhhyyssyhdddmmsdmsommdddhysyhhhhhhyyyyhdmmh```````````` `oho+.```````````o+ ``
# ````````````````````` .dd/o.``````hddddddddddmo-````````/: .ddhyyyyyd/ ````````` `sddhyyyyyyyyyyyhhd` `````````````````````` :dssssssssssssssssssssssssssssssssssssssshh ```````````` :hhsoooooooooyyyyd `````````````````````` oo////:::::::::+/::::::::////////////::::y: ````````````  ss`````````````oo ````````````````` y/hddddmyddddddddddddy-.:hdddddddddddddddddmmmmmmmmmNmmdmddddsmdmm:````````````.d.```````````````````` .mmhhmmyosh/-/:..-..-:.-syooymmdhhdmmdsymmN: ````````````  yo`````````````y+ ``
# ````````````````````` -dd:s-  ````hddddddddddmh-`       -o `hhyyyyyyd` `````````` `hhyyyyyyyyyyyyhds ``````````````````````` `dsossooosssssssssssssssssssooooooosoooosd+ ```````````` /yoooooooooosyyyho `````````````````````` :y:::::::::::::/+:::::::::::::::::::::::/h. ```````````` -h.````````````.d- ````````````````` s:sddddm+dddddddddddd:``./dddddddddddddddd/hmmmmmmmmmmddmdddshmdm+`````````````/h ````````````````````` +h..--......```````````...`.:/-..:++-..-od`````````````` :y.````````````.d.```
# ````````````````````` :dd:s/      hdddddddddddm-`       `o. +dyyyyyyy ``````````` /dyyyyyyyyyyyyhhm- ```````````````````````` syoosooooooooossoooooooooooooooooosoooosd- ``````````` /hoooooooooosyyyyd: `````````````````````` `y/:::::::::::::+::::::::::::::::::::://os ```````````` `h:`````````````oy `````````````````` +-:mdddmy+dhhhhhhhhdo````.odhhhhhhhhhhhdh-.dmmmmmmmmmmdmdddm/dmmh.````````````.h: ````````````````````` .d-.````````````````````````````````....+y ```````````` `h-`````````````ss ```
# ....................` +dd:so      ydddddddddddmo.        :+ .dyyyyyhy` `.......` .dyyyyyyyyyyyyyhdo `.......................` :doosoooooooooosoooooooooooooooooosooooydo- `.......` /hoooooooooosyyyyyh``......................` so:::::::::::::+:::::::::::::::::://+///s/``.........` os`````````````:d- `................` .``hddddd-hhhhhhhhhd.`````.hdhhhhhhhhhhd-`:mmmmmmmmmmddmdddd-mmm-````````````.ss `.....................  h/`````````````````````````````````````oo `.........`  s+`````````````/d.`...
# ....................` shd:os`     omddddddddddmd.`       `+. ohyyyyyd+ `....... `hhyyyyyyyyyyyyhdy``........................` .dooosooooooooosoooooooooooooooooosoossosyh `.....`` +hsoooooooosyyyyyyho `......................` /s::::::::::::://::::::::::::://///:::::/y. `.......` :h.```````````.:h/ `..................``` :mdddm:+dhhhhhhdo```````/dhhhhhhhhhd/``+mmhdmmmmmmdddddds/mm+````````````.+h``......................` os`````````````````````````````````````/h``.........` /y.```````````.:d: `...
# .................... `dyd-os.     -mddddddddddmo`        `:o`.dyyyyhhy. `.....` odyyyyyyyyyyyyhdh. ......................... `shoooooooooooooooooooooooooooooooosoooooyhy```....` ohyysoooossyyyyyyyyd. ......................` .s+///:::::::::::+:::::::::::/::::::::::/:oo. `.....` .h:```````````.:yo `......................` ymddm/.dhhhhhhd-```````.hhhhhhhhhhy.``smhhs:hmmmmdmdddm-omy.``````````.-+h- .......................` +y``````````````````````````````````````os```......` -h-```````````.:h+ `....
# .................... :dyd.sy-..````dmddddddddmy-`....-----.+: ohyyyyyyh- `...` +dyyyyyyyyyyyyhdh- `......................... `hyoooosooooooooosooooooooooooooooooooosssoys- `..` ohyyyyyyyyyyyyyyyyyhy `......................` :y:::::::::::::::+::::::::::::::::::::::---/s: `.... `y+``````````.-:yo``.......................` .dddm-`shyyyyhh.````````ohyyyyyyhd:``.dh+/.`.smmddmdddh`hd-``````````.-+h- `.......................` y+```````````````````````````````````````/y- `....` `h/``````````.-:h+ `.....
# ...................` ohyh`yo....---+dmmmmmmmmh:-.....``````.o.`hyyyyyyyh/ `.` :dhyyyyyyyyyyhhdh. `.......................... `hhysosoosssooooooooooooosssssooooossssooooooy+``` :dyyyyyyyyyyyyyyyyyyd: ......................` `o+---:::::-------+---:::::::::--------------:oo. `.` +y.````````.--/y+``.........................` /mms``:dyyyyho....`````-dyyyyyyhh```/y..`````/dmmdddd+`d/.````````.-:oh-``.......................` :h.````````.....```````````````````````````-s+``...` os.````````.--/h+``......
# ................... `dyys`o.```````.-smmmmmmd-``````````````-+ /dyyyyyyyh+`` -dhyyyyyyyyyhhddh. ...........................` ohsyyyysoooossssyyyssyyyssooooooooooooooooooooyy-  ohyyyyyyyyyyyyyyyyyhy `.....................` `o+-------::::::--:+-:::::::--------------------/o/`` .d-...```..-::+h/``...........................` yd.``.dyyyyd:.....````.hyyyyyydo```:.````````-ymdddd.os....```.--::sy.`........................` `h:````````.......```````````````````````````.+s.``` :h-...```..-::+h:``.......
# ..................` /dyh+`+````````.../hmmmm:````````````````/-`yhyyyyyyyhs`.ddhyyyyyhhhhdddh. ...........................` ohoooosssssooooooosyssoooooooooooooooooooooooooosy+`-dyyyyyyyyyyyyyyyyhh. ...................... `o+------------:::::+/::--------------------------:os:`yo-.....--:::oy-``...........................` .h:````dyyyyd.....:-````syyyyyyd/``````````````.omdds-d:.....--:::/yo``.........................  so````````......../````````````````````````````:y:  `h+-.....-::::sy.`.........
# ..................``hyyd../````````.....+dNs`````````````````.+`.hyyyyyyyyhyhddhhhhhhddddddh.`...........................``ohoooooooooooooooooosooooooooooooooooooooooooooooooyysdhhhyyyyyyyyyyyyhh- ......................` oo------------------+:-------------------------:://++yoh:::::::::::ss.`............................. `y+`````dyyyyy.....-o````ohyyyyyd+````````````````+mm-yo::::::::::+h/``.........................` +y.````````........o.````````````````````````````-y+ +y:::::::::::ys``..........
# .................` :dyyy -:````````......-+o``````````````````/: /hyyyyyyyyhmdddddddddddddh. ..........................` `syooooooooooooooooooosoooooooooooooooooooosooooooooooshdhhhhhhyyyyyyyhhy.`......................` /s-------------------+:----------------------:://+++++sdo:::::::::/yo``.............................` ss`````.dsssys.....-s````+hssyyyhy`````````````.:oyydoh/:::::::::oh-`..........................` :h.`````````........o.`````````````````````````````-hsd+:::::::::/h+``...........
# .................``yyyh+ /-`````````......//``````````````````.o` shyyyyyyyyhmhddddddddddy.`..........................` -yyooooosoooooooooooooosoooooooooooooooooooosooooooooooooydhyhhhhhhhhyyo:``......................` -y:-------------------+:------------------::///++++++:--+y/:::::::oh:``.............................` /h.`````+hsssys.....:+````+hssyyyydo-```````.-:oyyyyyymy::::::::/ys.`..........................` .h:```````````......-o```````````````````````````-:ohmmm/::::::::oy:`.............
# ................` :dyyd. +.``````````...../.```````````````````/- `hyyyyyyyyyhh/oyhdddddy``..........................``+hsooooosooooooooooooooosoooooooooooooooooooosooooooooooooymhhhhyhhd+-.```........................ `s+--------------------+-------------:::///++++++/::-::---/y/::::/ys.`..............................` -dh+````-hysssyy...../.````oysssyyyyyyso++oosyyhhyhhys+:yo::::::+h/``........................... `h/`````````````.....::`````````````````````.-:/oyhddddmmh+/::::/ys.`..............
# ................``hhyyy `o```````````````..````````````````````-+  :dyyyyyyyyydy+///oho+``..........................` +hooooooosooooooooooooooosooooooooooooooooooooosooooooosssyddssyhhhh: `............................ -h+//:::---------------+------::::////++++++//::/-----/:---+y/::/h+``............................... `hhyhs/:/yhyssssd.```..````.hyssyyyyyyyyyyyyyyyyhhyo:.```-h+::::oh-`............................` oy```````````````````.``````````````..-:/+oyhhdddhhhhdmhhdd/:::/h/``...............
# ...............` /dyyh/ .+`````````````````````````````````````.o   shyyyyyyyyhdy+oosy```...........................` hsoooooosooooooooooooooossooooooooooooooooooooosooosssyyhhdh/oo//+yy `............................` :y+++++++//////:::::::/+/////++++++++/+:::-:-----/----:/--::yo::/d- ...............................` oyshyyyyyyysssssho.````````+hsssyyyyyyyyyyyyyyhhs:.```````:h/:::sh``...........................` -Nhso+/::-------------.-----::/+oosyyhhddddhhhhhhhhhhmNddmmNs/::/d. ................
# ...............``hhyyd` -/``````````````````````````````````````+.  .dhyyyyyyyyhd+://d: ............................` yyssoooosooooooooosssssssssssooooooooooooooooosssyyyyhhhymmd::o+::/d- ............................ .y:/--:://////++++++++++o///+/:::/:----/:---:/----::----////+oy/::sh``.............................. .d-.hhyyyyyyssssyyh+-`````./hyyysyyyyyyyyyyyyhy+-``````````.oy/://d/ ...........................` hdddhdddddddhhhhhhhhhhhhddddddddddhhhhhhhyyyhhhyhhhhmNmmmhyyd+::/sy `...............
# ............... :dyyyh  /-````````````````````````````````````../-   +dyyyyyyyyydy///oh `...........................` /mhyyyyyyssssssssssssooosssssssssssssoosssssyyyyhhhhys+::ymmy:/s://sy `..........................` oo:/----/-----/-----/---+---/----:/-----/----/:----/:://+o+oyhh/://d/ .............................` os``-dyyyyyyyyyyyssyyo+//+syysyyyyyyyyyyyyyhy/.````````````-:ho://od``.......................... -mhhhhhhhhhdddddddddddddddddddddddddhyhhhyyyhhhhhhhhmNdhs/--:oy/://d: ...............
# ..............` shhyho  +-``````````````````````````````````.--.::   .dhyyyyyhhhyh////d- ...........................``oshhhhhyyyyyyyyyyys+/://///+syyyyyyyyyyyyyhhhhhys+:-````.:dmmsoh/://m- .......................... .y:/:---:/-----/-----+---+:--/-----/-----::---:/:://++++osyhddmms://oh `............................ `d:```+dyyyyyyyysssyssyyyyyyyyyyyyyyyyyyyyhho.`````````````.::+h/://d/ .........................` ydhhhhhhhhdmdmdddhhmddysyhhhddsydmdmmdhhhhhhhhhhhhhdm/-.``.-::h+://sy ...............
# ..............` hhhhd/  o-..````````````````````````......-://--//    +dyyhhhs/.`s+//oh: ........................... -+``-dmmhhhhhhhhhho//+++++++/:/ydhhhhhhyyddd+:-.```````..:/ymmmmmo//oh- .........................` /s:+::--/:----:/-----+---+:--/:----/:---::+:///++++osyyhdddmmddmd//+ys``............................ :h.````yhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhy-``````````````.::::ys//oh: ......................... `mdhhhdhhhdNmmmddmmdmmdddmdddmmmdmmmmmNNmdhhhhhhhhhdmo````.-:::oh//+ys `..............
# ............... .hhhd- .+/-/::---------------::--------...---:  -+    .yhy+:.   `:yss/``............................ /:```dmm-`.--:::/o:+-``````.-o//o.....```ddm: ````..-:/oyhdmmmmmmhss:``..........................` osoo+///+::::://:::::+::/s/:://::::/+///++ooossyhhddddddddmmmmdmmyso-``............................` so`````-hhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhh+.``````````````.:::::odss/``.......................... :NmdddddhdmNmmmmmmmdmmmdmmmdmmmmmmmmmmNmmmmdhhhhhddmd.```.-::::/dss+.`................
# ...............``o/hd. ::+`/`  `````.`.---. `.            `/`/  -+    ...` ````-/+/.``.............................. :+:--mmm-```    ////      -o+++/s`  `````sdms.-:/+oyhdmmmmmmmmmmh+.``............................` +dhhyssssooo++o++++++o+ohdho+oo+oooosssyyhhddddhhhhhhhhhhddmmmmds:``...............................``d:``````:dhyyyyyyyyyyyyyyyyyyyyyyyyyyyhh:``````````````.-:::/+os+-``...........................` oydmdhdddNdohhhyhmddmmhydmmddmmsyhhs+ommd+/ymdddddmmy.`.-::::/oso:``..................
# ............... .+ ./` /-+./`       . :.../  .            `+-+``:+ ```.````.:/+:.``................................. :mmdhmmm+:--....:+:+.``````-:o++s...---:/smmdyhdddmmmmmmmmmmdy/.``...............................` smdddddddddhhhhhhhhhhhhhdddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddho:``.................................. .m.``````./hhyyyyyyyyyyyyyyyyyyyhhhhhhhh-````````````..-::/oss+-``..............................` y+/Nmddmmyds+o/:/yhhymhymmsoss+::++///dh/``.:smmmmmmm:-::/+sso:``.....................
# ............... -+`.```o./:/-`````  .``---.  .````````--```-..``:o````--:+//-```.................................... /mmmmmmmmdddhyyysy+/+++oooo+++oyyyyyhhddddddddddddddddmddy+-```..................................` hdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhs/-``..................................... -d.```````./ydhyyyhhhhhhhhhhhhhhhhhhddh-```````````.-:/oss+:.``.................................``d:-Nmmmmh./dh/:::::::dmhmd/-::::::::/hh:``````ommmmmNy+sso/.``........................
# ............... -+:-``.o.`````-/-.``.-```````.-``````.+.```````.:o-/++/:.```........................................ /mmmmmmmdddddddddddy++oooooosyhdddddddddddddddddddddyo/-```......................................` yddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhs+:.``......................................... -d:...`````.:odmddddhhhhhhhhddddddddmd-``````...-/+sso/-```.....................................``h+:Nmmmms`.:ydy/:::::/ydy/---:::::/+hd/`````...hmmmdy+:.``............................
# ................```-://o:-.````-//:-.-````````..```..+-``.-::/++/:-.```.............................................``.:+shddmdddddddddddddhhhhhddddddddddddddddddhyo+:.```............................................``./oyhddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhyso/-.```.............................................```-/+++/:::::::ohdmdddddddddddddddmmm+...-/+oooo+:.```...........................................``-/shmmNy::::+ydhs+/::::::::://++ooyds..-:/+ooo+/-.``.................................
# ....................````.-:://+++++oo++//:::://++++++o////:-.````.......................................................````.:/+syhhddddddddddddddddddddhhyso+/-.````......................................................````-:+osyhhddddhhhhhhhhhhhhdddhhysoo/:-.````.......................................................````.-/++oossssdmmdddddddddddddddhoo++/:.````.....................................................```.-//+ooosydmdhysssssssyyyyyyyhhoo+/:-.```.......................................
# ............................```````..............````````.......................................................................``````...---------...````````.....................................................................```````...---------...```````........................................................................```````....------.....```````....................................................................```````..----------...```````...............................................
# ....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
# ....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

import pygame

# all-purpose handler class that coordinates the player, controller, and whatever else needs coordinating
# this is what allows a seamless transition between menu/game loops, keeps everything modular and independent, and
# solves a ton of headache causing problems with scope resolution
class handler():
    def __init__(self, controller, **kwargs):
        # the bare minimum a handler needs is a controller (coincidently, this is the bare minimum case in which a
        # handler is useful). It only takes a controller at first because the first handler is made right after the
        # driver.py::start loop is set to end (when player one hits start). At that point, a controller is all thats
        # available to be passed into class::handler
        self.controller = controller

        # most of this kwargs stuff is nearly useless, artifacts of a different version or stuff I added in case I
        # wanted to change it later, or I thought it would be easy to expand functionality in this direction
        # for whatever values aren't specified in kwargs, the initial state(s) are set to None, because handler needs
        # that field, but it can't be filled yet. They are added to handler via the attach method
        if 'console_message' in kwargs:
            print("from player_handler: ", kwargs['console_message'])
        if 'name' in kwargs:
            self.name = kwargs['name']
        else:
            self.name = 'generic'
        if 'player' in kwargs:
            self.player = kwargs['player']
        else:
            self.player = None
        if 'book' in kwargs:
            self.player = kwargs['book']
        else:
            self.book = None
        if 'menu' in kwargs:
            self.menu = kwargs['menu']
        else:
            self.menu = None
        self.hud = None
        self.missiles = pygame.sprite.Group()
        self.my_player_single = pygame.sprite.GroupSingle()
        self.other_players = pygame.sprite.Group()
        self.enemies = pygame.sprite.Group()

    #
    def attach(self, **kwargs):
        if 'player' in kwargs:
            self.player = kwargs['player']
        if 'book' in kwargs:
            self.book = kwargs['book']
        if 'menu' in kwargs:
            self.menu = kwargs['menu']
            print("attached menu: ", self.menu)
        if 'name' in kwargs:
            self.name = kwargs['name']

    def update_menu(self):
        #print("performing a menu update from player handler")
        #print("controller is type: ", type(self.controller))
        self.controller.update()
        face = self.controller.pull_face()
        A_accept = face['accept']
        Start_accept = face['start']
        selection = self.controller.pull_selectors()
        next = selection['next']
        prev = selection['prev']
        #print("selection is: ", selection)
        if next[1] and not next[0]:
            self.menu.next_book()
        elif prev[1] and not prev[0]:
            self.menu.prev_book()
        if (A_accept[1] and not A_accept[0]) or (Start_accept[1] and not Start_accept[0]):
            self.attach(book=self.menu.ready_up())

    def update(self, *args, **kwargs):
        # print("interface update: ", self)
        # updates the controller
        self.controller.update()

        #updates the player
        movement = self.controller.pull_movement()['move']
        facing = self.controller.pull_movement()['look']
        #self.player.move(move=movement)
        self.player.update(look=facing, move=movement)

        # updates the spellbook
        now, prev = self.controller.pull_face()['fire']
        # print("now= ", now, "prev= ", prev)
        sel_chk = self.controller.pull_selectors()['select']
        nxt_chk = self.controller.pull_selectors()['next']
        prv_chk = self.controller.pull_selectors()['prev']
        # its safe to call update more than once per frame for the spell book
        origin = self.player.rect.center
        if sel_chk != 9:
            self.book.update(origin, select_spell=sel_chk)
        elif nxt_chk[0] and not nxt_chk[1]:
            self.book.update(origin, cycle_spell='next')
        elif prv_chk[0] and not prv_chk[1]:
            self.book.update(origin, cycle_spell='prev')
        if now or prev:
            self.book.update(origin, fire=(now, prev), direction=self.player.facing,
                             missile_layer=self.missiles)
        self.book.update(origin, own_self=self.player, **kwargs)

        # updates spells
        # I just need to get the targeting data into the targeted spell
        self.missiles.update()

    # finishes pre-game prep by populating all of the necessary internal vars with the applicable data/references.
    # called by driver.py::class::screen. p_constr had to be passed in as a param to avoid importing stuff to
    # interface.py (which totally makes sense for reasons that are great and super important)
    def begin_game(self, p_constr, starting_room, player_num):
        # deletes a reference to the char_select_menu, since it is no longer needed, and should be garbage collected
        self.menu = None
        self.player = p_constr(self.book)
        self.book.pop_spells()
        # okay so I couldn't get around importing this one thing.
        from overlays import hud
        self.hud = hud(self.player, self.book, player_num)
        starting_room.add_players(self.player)
        self.my_player_single.add(self.player)

    # all of the draw_boxes method calls are for debugging and should be deleted prior to submission
    def draw(self, disp):
        self.player.draw(disp)
        self.player.draw_boxes(disp)
        self.missiles.draw(disp)
        for each in self.missiles:
            each.draw_boxes(disp)
        self.book.active_spell.draw(disp)
        self.hud.draw(disp)
        self.hud.draw_boxes(disp)
